name: NetworkBalance
version: '1.0-SNAPSHOT'
main: networkbalance.NetworkBalance
api-version: '1.21'
author: 'Thomas Froud'
commands:
  balance:
    description: Check your balance
  balancegive:
    description: Give a player balance
    usage: /balancegive <player> <amount>
    